### ISSUE TITLE
Blank Password Should Trigger an Error

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/wp-access-password#2]
A user can select the Generic Password setting, leave the field blank, and successfully save. 
This doesn't result in a "blank" password working, so there should probably be an error if they attempt to set their privacy to this setting, but fail to enter a password in the text field.

**Comment by mrjarbenne** [comment]
Did you sort this out as well @r-a-y

**Comment by r-a-y** [comment]
I haven't yet :(

I'll get to it some time today.  Will probably use javascript before 
submission to check if it is filled out or not.  If not, do not allow 
the submission until it is filled in.

**Comment by r-a-y** [comment]
Oops!  Referenced the wrong ticket! ;)

Commit 50e0c49 added some validation to check if the password is empty.  If it's empty, a red, inline error message is shown and form submission is prevented.

Validation requires JS.  I don't think that's a deal-breaker though.  Did some light testing and it works.  Let me know what you think.

**Comment by mrjarbenne** [comment]
I'll give it a shot.

On Jan 23, 2014, at 4:14 PM, "r-a-y" <notifications@github.com<mailto:notifications@github.com>> wrote:

I haven't yet :(

I'll get to it some time today. Will probably use javascript before
submission to check if it is filled out or not. If not, do not allow
the submission until it is filled in.

##

**Comment by mrjarbenne** [comment]
Works great.
