### ISSUE TITLE
Migration from WPMUDev Multisite Privacy

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/wp-access-password#3]
Migrations from Multisite privacy hold onto the Password Protected setting (-4 in the setting array), but the password doesn't carry over. Could the plugin query for that password, and pull it over if it exists? (if not, we can reach out manually).

**Comment by r-a-y** [comment]
Yeah, I was thinking about this myself.  Wasn't sure if we wanted to migrate the password over from the WPMUDev plugin to this one.  But since we need it, I can make it happen!

**Comment by r-a-y** [comment]
@mrjarbenne - Can you test the latest commits and see if this works?

**Comment by mrjarbenne** [comment]
Works perfectly
