### ISSUE TITLE
If People are Insistent...

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/wp-access-password#4]
If users balk at the idea that the password protection is protecting them from the world, but not from the community, would a plugin with this line work to hide their blog posts from the activity feed?

remove_action( 'save_post', 'bp_blogs_record_post', 10, 2 ); 

I got this from here: http://http://wordpress.org/support/topic/plugin-wordpress-mu-sitewide-tags-pages-swt-causing-double-posts-to-buddypress-activity-streams

**Comment by r-a-y** [comment]
If you're just activating this plugin on the site that is 
password-protected, then it should be fine.

If you're network-activating, you'd have to be careful where you would 
place the code.  If you place it without checking the blog in question, 
all blog posts will not be recorded.

**Comment by mrjarbenne** [comment]
It's the former. I would just offer up that plugin to the community as an option. I haven't decided yet if it's necessary. I feel like Zuckerburg, removing privacy to help promote community. I might get some backlash. ;)

**Comment by r-a-y** [comment]
> I feel like Zuckerburg, removing privacy to help promote community. I might get some backlash. ;)

:)  Btw, disregard the commit message above.  I referenced the wrong ticket in the commit message.
