### ISSUE TITLE
Redirect Not Occurring

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsbcommons/wp-access-password#5]
It may be that our cache is suddenly to severe on the new server, but we are finding that users aren't being redirected back to the homepage after entering the correct password using this password plugin. 

Using this site as an example: 

sandbox.commons.hwdsb.on.ca
with the password: password

Initially I am re-directed to here: 
http://sandbox.commons.hwdsb.on.ca/wp-login.php?action=access-pwd&redirect_to=http%3A%2F%2Fsandbox.commons.hwdsb.on.ca%2F

but upon successful entry of the password, the redirect doesn't occur. If I manually navigate back to the homepage, I have indeed authenticated and can gain entry. 

Is there anything we can do on the plugin side to fix this, or is there something you could suggest on the server side?

**Comment by r-a-y** [comment]
Just tested this on my local nginx setup and it's working.

Perhaps something is missing in your nginx fastcgi conf file?
http://wiki.nginx.org/PHPFcgiExample

The server looks like it is caching pages even when the WP Access Password cookie is in use.  Cookies starting with `wp-accesspwd_` needs to be whitelisted from caching.

**Comment by mrjarbenne** [comment]
Thanks. I'll hit up the host. We aren't managing the server internally anymore.

**Comment by mrjarbenne** [comment]
Is there any way to debug what might be missing in the conf file?

**Comment by mrjarbenne** [comment]
He white listed the cookie in the cache. Problem solved.

**Comment by r-a-y** [comment]
Nice!
